import type { Job } from "@/types";

export const placeholderJobs: Job[] = [
  {
    id: "preview-lighthouse-product-designer",
    title: "Product Designer, Calm Systems",
    description:
      "Shape the tools that help independent teams do their best work without adding more noise to their day.",
    location: "Lagos, Nigeria / Hybrid",
    salary: "$52k - $68k",
    type: "FULL_TIME",
    category: "Design",
    apply_url: "#",
    status: "ACTIVE",
    featured: true,
    isPlaceholder: true,
    company_id: "preview-lighthouse",
    created_at: "2026-09-18T09:00:00.000Z",
    company: {
      id: "preview-lighthouse",
      name: "Lighthouse Works",
      website: "#",
      description: "Tools for teams with good taste and important work.",
      location: "Lagos, Nigeria",
      user_id: "preview",
      created_at: "2026-09-01T09:00:00.000Z",
    },
  },
  {
    id: "preview-morrow-operations-lead",
    title: "Operations Lead, New Markets",
    description:
      "Build the rituals, systems, and partnerships that turn a promising product into a trusted everyday service.",
    location: "Remote / Africa & Europe",
    salary: "$60k - $82k",
    type: "REMOTE",
    category: "Operations",
    apply_url: "#",
    status: "ACTIVE",
    featured: false,
    isPlaceholder: true,
    company_id: "preview-morrow",
    created_at: "2026-09-16T09:00:00.000Z",
    company: {
      id: "preview-morrow",
      name: "Morrow Market",
      website: "#",
      description: "Making cross-border commerce feel close to home.",
      location: "Remote",
      user_id: "preview",
      created_at: "2026-09-01T09:00:00.000Z",
    },
  },
  {
    id: "preview-cinder-content-strategist",
    title: "Content Strategist, Brand Voice",
    description:
      "Give a growing climate company a voice that is precise, human, and impossible to mistake for corporate filler.",
    location: "Accra, Ghana / Flexible",
    salary: "$34k - $46k",
    type: "CONTRACT",
    category: "Marketing",
    apply_url: "#",
    status: "ACTIVE",
    featured: false,
    isPlaceholder: true,
    company_id: "preview-cinder",
    created_at: "2026-09-13T09:00:00.000Z",
    company: {
      id: "preview-cinder",
      name: "Cinder Energy",
      website: "#",
      description: "Practical climate infrastructure for growing cities.",
      location: "Accra, Ghana",
      user_id: "preview",
      created_at: "2026-09-01T09:00:00.000Z",
    },
  },
];
